### ISSUE TITLE
Bind properties from config object

### ISSUE THREAD

**Issue by eduboxgithub** [Mawi137/ngx-image-cropper#143]
Hello,

First of all thank you for your component. I'm using it and it's really great.

But I have found an issue. If I try to set some input properties from and config object the properties are not correctly binded.

For example this works:

```
<image-cropper	(imageCropped)="imageCropped($event)"
				(imageLoaded)="imageLoaded()"
				(loadImageFailed)="loadImageFailed()"
				[imageChangedEvent]="imageChangedEvent"
				[maintainAspectRatio]="true"
				[imageBase64]="imageBase64"
				[roundCropper]="false"
				[aspectRatio]="1/1"
				[resizeToWidth]="160"
				format="png">
</image-cropper>
```

But this does not work:
```
ngOnInit()
{
	this.config= 
	{
		AspectRatio: "4 / 3",
		ResizeToWidth: "800",
		ImageFormat: "png"
	};
}

<image-cropper	(imageCropped)="imageCropped($event)"
				(imageLoaded)="imageLoaded()"
				(loadImageFailed)="loadImageFailed()"
				[imageChangedEvent]="imageChangedEvent"
				[maintainAspectRatio]="true"
				[imageBase64]="imageBase64"
				[roundCropper]="false"
				[aspectRatio]="config.AspectRatio"
				[resizeToWidth]="config.ResizeWidth"
				[format]="config.ImageFormat">
</image-cropper>
```

And I get this error:

```
core.js:15714 ERROR DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at resizeCanvas (http://localhost:8100/default~pages-employees-employees-module~pages-roadsignsmapping-roadsignsmapping-module.js:214:23)
    at ImageCropperComponent.push../node_modules/ngx-image-cropper/fesm5/ngx-image-cropper.js.ImageCropperComponent.crop (http://localhost:8100/default~pages-employees-employees-module~pages-roadsignsmapping-roadsignsmapping-module.js:935:21)
    at ImageCropperComponent.push../node_modules/ngx-image-cropper/fesm5/ngx-image-cropper.js.ImageCropperComponent.doAutoCrop (http://localhost:8100/default~pages-employees-employees-module~pages-roadsignsmapping-roadsignsmapping-module.js:899:18)
    at ImageCropperComponent.push../node_modules/ngx-image-cropper/fesm5/ngx-image-cropper.js.ImageCropperComponent.resetCropperPosition (http://localhost:8100/default~pages-employees-employees-module~pages-roadsignsmapping-roadsignsmapping-module.js:643:14)
    at ImageCropperComponent.push../node_modules/ngx-image-cropper/fesm5/ngx-image-cropper.js.ImageCropperComponent.checkImageMaxSizeRecursively (http://localhost:8100/default~pages-employees-employees-module~pages-roadsignsmapping-roadsignsmapping-module.js:523:18)
    at http://localhost:8100/default~pages-employees-employees-module~pages-roadsignsmapping-roadsignsmapping-module.js:506:51
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:8100/polyfills.js:2768:31)
    at Object.onInvokeTask (http://localhost:8100/vendor.js:53090:33)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:8100/polyfills.js:2767:60)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (http://localhost:8100/polyfills.js:2540:47)
    at push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask (http://localhost:8100/polyfills.js:2843:34)
    at ZoneTask.invoke (http://localhost:8100/polyfills.js:2832:48)
    at timer (http://localhost:8100/polyfills.js:4626:29)
```

**Comment by Mawi137** [comment]
ResizeToWidth and AspectRatio should be of type number, you have them as a string in your example. 4 / 3 equals 1.33333. It's written as 4 / 3 because it's easier to read like that.

**Comment by eduboxgithub** [comment]
Ohhh my goodness... What a rookie mistake... I'm sorry to have wasted your time. =/

I'm using the 1, 1.33 and 1.77 aspect ratios now.

It's all good, it's working now... Thank you for your help. =)

**Comment by albert-hoffman** [comment]
Thanks, solution got worked.

**Comment by saggio89** [comment]
Had a very similar issue & found this... ugh I spent so long trying to figure out what was wrong haha thanks @Mawi137
