### ISSUE TITLE
image src is not accepting url but works fine with local image in assset folder

### ISSUE THREAD

**Issue by Ashok-Kumar-Venaktesh** [Mawi137/ngx-image-cropper#155]
core.js:14597 ERROR DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
    at ImageCropperComponent.push../node_modules/ngx-image-cropper/fesm5/ngx-image-cropper.js.ImageCropperComponent.cropToBase64 (http://localhost:4200/vendor.js:149893:38)
    at ImageCropperComponent.push../node_modules/ngx-image-cropper/fesm5/ngx-image-cropper.js.ImageCropperComponent.cropToOutputType (http://localhost:4200/vendor.js:149870:38)
    at ImageCropperComponent.push../node_modules/ngx-image-cropper/fesm5/ngx-image-cropper.js.ImageCropperComponent.crop (http://localhost:4200/vendor.js:149824:29)
    at ImageCropperComponent.push../node_modules/ngx-image-cropper/fesm5/ngx-image-cropper.js.ImageCropperComponent.doAutoCrop (http://localhost:4200/vendor.js:149786:18)
    at ImageCropperComponent.push../node_modules/ngx-image-cropper/fesm5/ngx-image-cropper.js.ImageCropperComponent.resetCropperPosition (http://localhost:4200/vendor.js:149530:14)
    at ImageCropperComponent.push../node_modules/ngx-image-cropper/fesm5/ngx-image-cropper.js.ImageCropperComponent.checkImageMaxSizeRecursively (http://localhost:4200/vendor.js:149410:18)
    at http://localhost:4200/vendor.js:149393:51
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:2766:31)
    at Object.onInvokeTask (http://localhost:4200/vendor.js:75394:33)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:2765:36)
defaultErrorLogger @ core.js:14597
push../node_modules/@angular/core/fesm5/core.js.ErrorHandler.handleError @ core.js:14645
next @ core.js:16628
schedulerFn @ core.js:12609
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:196
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next @ Subscriber.js:134
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ Subscriber.js:77
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:54
push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next @ Subject.js:47
push../node_modules/@angular/core/fesm5/core.js.EventEmitter.emit @ core.js:12593
(anonymous) @ core.js:16178
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:388
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:138
push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular @ core.js:16115
onHandleError @ core.js:16178
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.handleError @ zone.js:392
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:191
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:496
ZoneTask.invoke @ zone.js:485
timer @ zone.js:2054
setTimeout (async)
scheduleTask @ zone.js:2075
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:407
onScheduleTask @ zone.js:297
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:401
push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:232
push../node_modules/zone.js/dist/zone.js.Zone.scheduleMacroTask @ zone.js:255
scheduleMacroTaskWithCurrentZone @ zone.js:1114
(anonymous) @ zone.js:2090
proto.(anonymous function) @ zone.js:1394
push../node_modules/ngx-image-cropper/fesm5/ngx-image-cropper.js.ImageCropperComponent.imageLoadedInView @ ngx-image-cropper.js:489
(anonymous) @ ImageCropperComponent.html:7
handleEvent @ core.js:21673
callWithDebugContext @ core.js:22767
debugHandleEvent @ core.js:22470
dispatchEvent @ core.js:19122
(anonymous) @ core.js:19569
(anonymous) @ platform-browser.js:993
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:421
onInvokeTask @ core.js:16147
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:420
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:188
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:496
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
load (async)
customScheduleGlobal @ zone.js:1666
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:407
onScheduleTask @ zone.js:297
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:401
push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:232
push../node_modules/zone.js/dist/zone.js.Zone.scheduleEventTask @ zone.js:258
(anonymous) @ zone.js:1831
desc.set @ zone.js:1244
push../node_modules/ngx-image-cropper/fesm5/ngx-image-cropper.js.ImageCropperComponent.loadBase64Image @ ngx-image-cropper.js:471
set @ ngx-image-cropper.js:360
updateProp @ core.js:20871
checkAndUpdateDirectiveInline @ core.js:20622
checkAndUpdateNodeInline @ core.js:21929
checkAndUpdateNode @ core.js:21891
debugCheckAndUpdateNode @ core.js:22525
debugCheckDirectivesFn @ core.js:22485
(anonymous) @ AssetExtractionComponent.html:51
debugUpdateDirectives @ core.js:22477
checkAndUpdateView @ core.js:21873
callViewAction @ core.js:22114
execEmbeddedViewsAction @ core.js:22077
checkAndUpdateView @ core.js:21874
callViewAction @ core.js:22114
execEmbeddedViewsAction @ core.js:22077
checkAndUpdateView @ core.js:21874
callViewAction @ core.js:22114
execComponentViewsAction @ core.js:22056
checkAndUpdateView @ core.js:21879
callViewAction @ core.js:22114
execEmbeddedViewsAction @ core.js:22077
checkAndUpdateView @ core.js:21874
callViewAction @ core.js:22114
execComponentViewsAction @ core.js:22056
checkAndUpdateView @ core.js:21879
callViewAction @ core.js:22114
execComponentViewsAction @ core.js:22056
checkAndUpdateView @ core.js:21879
callWithDebugContext @ core.js:22767
debugCheckAndUpdateView @ core.js:22445
push../node_modules/@angular/core/fesm5/core.js.ViewRef_.detectChanges @ core.js:20254
(anonymous) @ core.js:16888
push../node_modules/@angular/core/fesm5/core.js.ApplicationRef.tick @ core.js:16888
(anonymous) @ core.js:16779
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:388
onInvoke @ core.js:16156
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:387
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:138
push../node_modules/@angular/core/fesm5/core.js.NgZone.run @ core.js:16070
next @ core.js:16779
schedulerFn @ core.js:12609
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:196
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next @ Subscriber.js:134
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ Subscriber.js:77
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:54
push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next @ Subject.js:47
push../node_modules/@angular/core/fesm5/core.js.EventEmitter.emit @ core.js:12593
checkStable @ core.js:16125
onHasTask @ core.js:16169
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.hasTask @ zone.js:441
push../node_modules/zone.js/dist/zone.js.ZoneDelegate._updateTaskCount @ zone.js:461
push../node_modules/zone.js/dist/zone.js.Zone._updateTaskCount @ zone.js:285
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:205
drainMicroTaskQueue @ zone.js:595
Promise.then (async)
scheduleMicroTask @ zone.js:578
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:410
push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:232
push../node_modules/zone.js/dist/zone.js.Zone.scheduleMicroTask @ zone.js:252
scheduleResolveOrReject @ zone.js:862
ZoneAwarePromise.then @ zone.js:962
push../node_modules/@angular/core/fesm5/core.js.PlatformRef.bootstrapModule @ core.js:16660
./src/main.ts @ main.ts:12
__webpack_require__ @ bootstrap:83
0 @ main.ts:13
__webpack_require__ @ bootstrap:83
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js:1

**Comment by Ashok-Kumar-Venaktesh** [comment]
const toDataURL = url => fetch(url)
  .then(response => response.blob())
  .then(blob => new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.onloadend = () => resolve(reader.result)
    reader.onerror = reject
    reader.readAsDataURL(blob)
  }))


toDataURL('https://www.gravatar.com/avatar/d50c83cc0c6523b4d3f6085295c953e0')
  .then(dataUrl => {
    console.log('RESULT:', dataUrl)
  })

**Comment by Ashok-Kumar-Venaktesh** [comment]
We need convert the image to base64.  Thats it

**Comment by Ashok-Kumar-Venaktesh** [comment]
Refer below for more details:

https://stackoverflow.com/questions/6150289/how-to-convert-image-into-base64-string-using-javascript/20285053#20285053
