### ISSUE TITLE
ERROR RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Lizonchik** [Mawi137/ngx-image-cropper#19]
Hi. When I uploaded the image with size more then 3 Mb I saw this error (see below).
What can you advise about this?

> ImageCropperComponent.html:3 ERROR RangeError: Maximum call stack size exceeded
    at RegExp.[Symbol.match] (<anonymous>)
    at String.match (native)
    at sanitizeUrl (webpack-internal:///../../../platform-browser/@angular/platform-browser.es5.js:3438:44)
    at DomSanitizerImpl.sanitize (webpack-internal:///../../../platform-browser/@angular/platform-browser.es5.js:4008:24)
    at setElementProperty (webpack-internal:///../../../core/@angular/core.es5.js:9600:78)
    at checkAndUpdateElementValue (webpack-internal:///../../../core/@angular/core.es5.js:9520:13)
    at checkAndUpdateElementInline (webpack-internal:///../../../core/@angular/core.es5.js:9454:24)
    at checkAndUpdateNodeInline (webpack-internal:///../../../core/@angular/core.es5.js:12537:20)
    at checkAndUpdateNode (webpack-internal:///../../../core/@angular/core.es5.js:12484:16)
    at debugCheckAndUpdateNode (webpack-internal:///../../../core/@angular/core.es5.js:13341:59)

**Comment by Mawi137** [comment]
It seems like the sanitizer of Angular isn't able to handle such large images. I found a solution that bypasses the security checks. I'll let you know when the fix is released.

**Comment by Mawi137** [comment]
Should be fixed in 0.1.25!

**Comment by Lizonchik** [comment]
Cool. It works)
Thank you!

**Comment by takrout** [comment]
Hello, I have the same issue with the version 2.0.3

**Comment by SwapnilHamsa** [comment]
Hello, I have the same issue with version 6.2.2
