### ISSUE TITLE
It's not working with angular8 Server-side Rendering (SSR) ? 

### ISSUE THREAD

**Issue by manjitsingh91** [Mawi137/ngx-image-cropper#191]
Hi Team, 

I have used this with angular8 and it's working fine. But now I have implemented angular Server-side Rendering (SSR) [angular universal](https://angular.io/guide/universal) and it's showing me the following error.

throw new Error("NotYetImplemented");
  ^

Error: NotYetImplemented
    at HTMLCanvasElement.exports.nyi (F:\Vig\hn-ssr\hn\ClientApp\dist\server.js:24471:9)
    at dg (F:\Vig\hn-ssr\hn\ClientApp\dist\server\main.js:57184:296)
    at F:\Vig\hn-ssr\hn\ClientApp\dist\server\main.js:57619:216
    at ADia (F:\Vig\hn-ssr\hn\ClientApp\dist\server\main.js:57079:22)
    at Object.ADia (F:\Vig\hn-ssr\hn\ClientApp\dist\server\main.js:57081:2)
    at __webpack_require__ (F:\Vig\hn-ssr\hn\ClientApp\dist\server\main.js:20:30)
    at Object.q+2X (F:\Vig\hn-ssr\hn\ClientApp\dist\server\main.js:186355:20)
    at __webpack_require__ (F:\Vig\hn-ssr\hn\ClientApp\dist\server\main.js:20:30)
    at Object.xkkA (F:\Vig\hn-ssr\hn\ClientApp\dist\server\main.js:199969:72)
    at __webpack_require__ (F:\Vig\hn-ssr\hn\ClientApp\dist\server\main.js:20:30)

**Comment by ninjavis** [comment]
From what I've read about SSR, and don't quote me on this, you need to exclude this script from being loaded when Angular Universal renders your page. Not sure exactly how though, but maybe you can find something about this..

**Comment by ninjavis** [comment]
I think this is the solution:

From https://www.widerfunnel.com/server-side-testing/

`///////////////////
// app.module.ts //
///////////////////

import { AppComponent } from './../components/app.component';

// ...

@NgModule({
	declarations: [ AppComponent ]

})

export class AppModule {}

//////////////////////
// app.component.ts //
//////////////////////

import { PLATFORM_ID } from '@angular/core';
import { isPlatformBrowser, isPlatformServer } from '@angular/common';

@Component({
	template: '<button class="wf-test">Experiment</button>',
	styles: [ '.wf-test { background: {{ variationColor }} }' ]
})

export class AppComponent {

	constructor(@Inject(PLATFORM_ID) private platformId: Object, ) {
		
	}

	ngOnInit() {
		
		if (isPlatformServer(this.platformId)) {
		     
			// your logic here
			
		}

                if ( isPlatformBrowser(this.platformId) {  
                    // your logic here
                 }

	}

}`

**Comment by Mawi137** [comment]
Hi all, it seems that error comes from the HTML Canvas that is used to crop the image. I don't have any experience with Angular Universal so if you find a solution that can be added to the image cropper, feel free to open a PR!
