### ISSUE TITLE
ERROR DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.

### ISSUE THREAD

**Issue by Sampath-Lokuge** [Mawi137/ngx-image-cropper#524]
Hi,

Please let us know why this error. Thanks!

Note: I need to touch the device screen to show the `image-cropper` component. I hope it is due to this error.

.html

```
 <image-cropper
    [imageBase64]="photoUrl"
    [maintainAspectRatio]="true"
    [aspectRatio]="1 / 1"
    [resizeToWidth]="512"
    [canvasRotation]="rotation"
    format="jpeg"
    (imageCropped)="imageCropped($event)"
    (imageLoaded)="imageLoaded()"
    (cropperReady)="cropperReady()"
    (loadImageFailed)="loadImageFailed()"
    class="photo"
  ></image-cropper>
```

.ts

```
ngOnInit(): void {
 this.profileDataService.userProfilePhotoChanged$.subscribe((res) => {
      this.photoUrl = res;
    });
}
```
**Error**

```
node_modules_ionic_core_dist_esm_ion-modal_entry_js.js:2 ERROR DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.
    at resizeCanvas (http://192.168.8.145:8100/src_app_modules_profile_profile_module_ts.js:6960:21)
    at CropService.crop (http://192.168.8.145:8100/src_app_modules_profile_profile_module_ts.js:7077:7)
    at ImageCropperComponent.crop (http://192.168.8.145:8100/src_app_modules_profile_profile_module_ts.js:8276:39)
    at ImageCropperComponent.doAutoCrop (http://192.168.8.145:8100/src_app_modules_profile_profile_module_ts.js:8269:12)
    at ImageCropperComponent.resetCropperPosition (http://192.168.8.145:8100/src_app_modules_profile_profile_module_ts.js:8045:10)
    at ImageCropperComponent.checkImageMaxSizeRecursively (http://192.168.8.145:8100/src_app_modules_profile_profile_module_ts.js:7993:12)
    at http://192.168.8.145:8100/src_app_modules_profile_profile_module_ts.js:7982:29
    at timer (http://192.168.8.145:8100/polyfills.js:11225:33)
    at ZoneDelegate.invokeTask (http://192.168.8.145:8100/polyfills.js:8183:173)
    at Object.onInvokeTask (http://192.168.8.145:8100/vendor.js:147056:25)
```

package.json

```
{
 
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "lint": "ng lint"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "14.1.0",
    "@angular/cdk": "14.1.0",
    "@angular/common": "14.1.0",
    "@angular/core": "14.1.0",
    "@angular/fire": "7.4.1",
    "@angular/forms": "14.1.0",
    "@angular/google-maps": "14.1.0",
    "@angular/platform-browser": "14.1.0",
    "@angular/platform-browser-dynamic": "14.1.0",
    "@angular/router": "14.1.0",
    "@capacitor/android": "3.6.0",
    "@capacitor/app": "1.1.1",
    "@capacitor/browser": "1.0.3",
    "@capacitor/camera": "1.0.5",
    "@capacitor/core": "3.6.0",
    "@capacitor/geolocation": "1.1.0",
    "@capacitor/haptics": "1.1.4",
    "@capacitor/ios": "3.6.0",
    "@capacitor/keyboard": "1.2.3",
    "@capacitor/push-notifications": "1.0.4",
    "@capacitor/splash-screen": "1.1.6",
    "@capacitor/status-bar": "1.0.8",
    "@capacitor/storage": "1.1.0",
    "@ionic-native/app-availability": "5.36.0",
    "@ionic-native/call-number": "5.36.0",
    "@ionic-native/core": "5.36.0",
    "@ionic-native/in-app-browser": "5.36.0",
    "@ionic-native/photo-viewer": "5.36.0",
    "@ionic-native/screen-orientation": "5.36.0",
    "@ionic-native/social-sharing": "5.36.0",
    "@ionic/angular": "6.1.9",
    "@types/lodash": "4.14.172",
    "call-number": "1.0.1",
    "com-sarriaroman-photoviewer": "1.2.5",
    "cordova-plugin-appavailability": "0.4.2",
    "cordova-plugin-inappbrowser": "5.0.0",
    "cordova-plugin-screen-orientation": "3.0.2",
    "cordova-plugin-x-socialsharing": "6.0.3",
    "es6-promise-plugin": "4.2.2",
    "firebase": "9.8.2",
    "lodash": "4.17.21",
    "ng-cloudimage-responsive": "4.0.0",
    "ngx-image-cropper": "^6.2.2",
    "primeicons": "5.0.0",
    "primeng": "14.0.0",
    "rxjs": "6.6.0",
    "tslib": "2.2.0",
    "zone.js": "0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "14.1.0",
    "@angular-eslint/builder": "14.0.2",
    "@angular-eslint/eslint-plugin": "14.0.2",
    "@angular-eslint/eslint-plugin-template": "14.0.2",
    "@angular-eslint/template-parser": "14.0.2",
    "@angular/cli": "14.1.0",
    "@angular/compiler": "14.1.0",
    "@angular/compiler-cli": "14.1.0",
    "@angular/language-service": "14.1.0",
    "@capacitor/cli": "3.6.0",
    "@ionic/angular-toolkit": "6.0.0",
    "@types/node": "12.11.1",
    "@typescript-eslint/eslint-plugin": "5.29.0",
    "@typescript-eslint/parser": "5.29.0",
    "eslint": "8.18.0",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jsdoc": "30.7.6",
    "eslint-plugin-prefer-arrow": "1.2.2",
    "prettier": "2.3.2",
    "ts-node": "8.3.0",
    "typescript": "4.7.3"
  },

}

```

**Comment by Sampath-Lokuge** [comment]
This is due to the wrong `photoUrl`. i.e. not set the correct base64 image.
