### ISSUE TITLE
Angular 16.2 - Inject Error

### ISSUE THREAD

**Issue by Hyperjase74** [Mawi137/ngx-image-cropper#586]
When following the basic configuration as defined under the README.md, I firstly receive one error:

```
src/app/components/profile/profile.component.html:38:37 - error TS2554: Expected 1 arguments, but got 0.

38                      (imageLoaded)="imageLoaded()"
                                       ~~~~~~~~~~~

  src/app/components/profile/profile.component.ts:8:16
    8   templateUrl: './profile.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component ProfileComponent.
```
But, after following the responses [here](https://stackoverflow.com/questions/65535056/ngx-image-cropper-imageloaded-not-passing-any-image-data-to-typescript-file-ev), we then move on to a new error which I'm unsure on how to fix (unsure if this a user error, caused by my misunderstanding).

```
ERROR Error: Uncaught (in promise): Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.io/errors/NG0203
Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.io/errors/NG0203
    at injectInjectorOnly (core.mjs:731:15)
    at ɵɵinject (core.mjs:744:60)
    at Module.ɵɵdirectiveInject (core.mjs:11781:16)
    at NodeInjectorFactory.ImageCropperComponent_Factory [as factory] (ngx-image-cropper.mjs:326:98)
    at getNodeInjectable (core.mjs:4758:44)
    at instantiateAllDirectives (core.mjs:12612:27)
    at createDirectivesInstances (core.mjs:12028:5)
    at Module.ɵɵelementStart (core.mjs:16319:9)
    at ProfileComponent_Template (profile.component.html:33:7)
    at executeTemplate (core.mjs:11986:13)
    at resolvePromise (zone.js:1193:31)
    at resolvePromise (zone.js:1147:17)
    at zone.js:1260:17
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at core.mjs:10735:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:10735:36)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Object.onInvokeTask (core.mjs:11048:33)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Zone.runTask (zone.js:173:47)
```
The page doesn't load anything whatsoever.

And for clarity, here is my implementation logic (which only covers ngx-image-cropper):

**app.module.ts**
````
import { ImageCropperModule } from 'ngx-image-cropper';

@NgModule({
    imports: [
      ImageCropperModule
    ]
})
````

**profile.component.ts**
```
import { DomSanitizer } from '@angular/platform-browser';
import { ImageCroppedEvent, LoadedImage } from 'ngx-image-cropper';
export class ProfileComponent {

  imageChangedEvent: any = '';
  croppedImage: any = '';

  constructor(
    private sanitizer: DomSanitizer
  ) { }

  fileChangeEvent(event: any): void {
    this.imageChangedEvent = event;
  }
  imageCropped(event: ImageCroppedEvent) {
    this.croppedImage = this.sanitizer.bypassSecurityTrustUrl(event.objectUrl!);
    // event.blob can be used to upload the cropped image
  }
  imageLoaded(image: LoadedImage) {
    // show cropper
  }
  cropperReady() {
    // cropper ready
  }
  loadImageFailed() {
    // show message
  }
}
```

**profile.component.html**
```
 <fieldset>
      <legend>User Image</legend>
      <input type="file" (change)="fileChangeEvent($event)" />
      
      <image-cropper [imageChangedEvent]="imageChangedEvent"
                     [maintainAspectRatio]="true"
                     [aspectRatio]="1 / 1"
                     format="png"
                     (imageCropped)="imageCropped($event)"
                     (imageLoaded)="imageLoaded($event)"
                     (cropperReady)="cropperReady()"
                     (loadImageFailed)="loadImageFailed()"></image-cropper>

      <img [src]="croppedImage" />

    </fieldset>
```

Am I doing something wrong here, or is this broken for Angular 16.2?

**Comment by Hyperjase74** [comment]
I've been able to fix this - it appears when I attempted to use another Angular plugin, I got the same message, so this is more to do with Angular overall rather than this plugin.

For reference, [this is how it was fixed](https://stackoverflow.com/a/61801741/5679808).
