### ISSUE TITLE
I get error  FileList is not defined run on angular 18.2.6

### ISSUE THREAD

**Issue by kapookengpro** [Mawi137/ngx-image-cropper#663]
Can you fix this ?

ERROR ReferenceError: FileList is not defined
    at _ImageCropperComponent.isValidImageChangedEvent (eval at instantiateModule (file:///G:/Project%20Outsouce/Thesis/FE/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:52905:24), <anonymous>:1239:29)
    at _ImageCropperComponent.onChangesInputImage (eval at instantiateModule (file:///G:/Project%20Outsouce/Thesis/FE/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:52905:24), <anonymous>:1224:46)
    at _ImageCropperComponent.ngOnChanges (eval at instantiateModule (file:///G:/Project%20Outsouce/Thesis/FE/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:52905:24), <anonymous>:1191:10)

**Comment by gtaborga** [comment]
Is this project maintained? I'm having the same issue on Angular 19.2.6
